"""add proposal analysis tables

Revision ID: 71ec1074c5e1
Revises: 67dd8aecd169
Create Date: 2026-10-05 23:54:54.716046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71ec1074c5e1'
down_revision: Union[str, Sequence[str], None] = '67dd8aecd169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bawc_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('documents_found', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bawc_analyses_proposal_id'), 'bawc_analyses', ['proposal_id'], unique=False)
    op.create_table('financial_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('annual_premium', sa.Float(), nullable=True),
    sa.Column('sum_assured', sa.Float(), nullable=True),
    sa.Column('premium_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('sum_assured_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('account_age_days', sa.Integer(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_analyses_proposal_id'), 'financial_analyses', ['proposal_id'], unique=False)
    op.create_table('insurance_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('existing_policy_count', sa.Integer(), nullable=True),
    sa.Column('total_existing_sum_assured', sa.Float(), nullable=True),
    sa.Column('multiple_insurer_flag', sa.Boolean(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_analyses_proposal_id'), 'insurance_analyses', ['proposal_id'], unique=False)
    op.create_table('kyc_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_analyses_proposal_id'), 'kyc_analyses', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_analyses_proposal_id'), table_name='kyc_analyses')
    op.drop_table('kyc_analyses')
    op.drop_index(op.f('ix_insurance_analyses_proposal_id'), table_name='insurance_analyses')
    op.drop_table('insurance_analyses')
    op.drop_index(op.f('ix_financial_analyses_proposal_id'), table_name='financial_analyses')
    op.drop_table('financial_analyses')
    op.drop_index(op.f('ix_bawc_analyses_proposal_id'), table_name='bawc_analyses')
    op.drop_table('bawc_analyses')
    # ### end Alembic commands ###
